language: minimal

stages:
  - name: fast_check

jobs:
  include:
    - stage: fast_check
      name: Shell linter
      language: shell
      script:
        - bash -c 'shopt -s globstar; shellcheck -e SC1117 **/*.sh'

    - stage: fast_check
      name: Fast build
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - docker pull fritzing/build:bionic
      script:
        - docker/build-linux.sh

