name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install HomeBrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew --version

      - name: install Qt5 with Brew
        run: |
          brew install qt5 
          
      - name: Build and Install LibGit2
        run: |
         mkdir -p ../libgit2/build
          wget -q -O - https://github.com/libgit2/libgit2/archive/v0.28.1.tar.gz | tar xz && mv libgit2-0.28.1/* ../libgit2/
          (cd ../libgit2/build && cmake -D BUILD_SHARED_LIBS=OFF .. && cmake --build .)
          (cd .. && wget -q -O - https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
          echo "libgit2 is build"
          
      - name: Get and Install Boost
        run: |
          (cd .. && wget -q -O - https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
          echo "boost installed"

      - name: Deploy and Build Fritzing
        run: |
             ls /usr/local/opt
             pwd
             ls -alrt
             ./tools/deploy_fritzing_mac.sh
             echo "done DEPLOY SCRIPT"
             
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch
          git remote add releaseorigin https://github.com/el-j/freetzing-macosRelease.git
          git status
          git add .
          git status
          git commit -m "push release now"
          git push -u releaseorigin master
