name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          host: 'mac'
      - name: Install dependencies LibGit&Boost
        run: |
         mkdir -p ../libgit2/build
          wget -q -O - https://github.com/libgit2/libgit2/archive/v0.28.1.tar.gz | tar xz && mv libgit2-0.28.1/* ../libgit2/
          (cd ../libgit2/build && cmake -D BUILD_SHARED_LIBS=OFF .. && cmake --build .)
          (cd .. && wget -q -O - https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
      - name: Deploy and Build Fritzing
        run: |
             ls /usr/local/opt
             tools/deploy_fritzing_mac.sh
